export const list1 = {
  '1': "Kelly's Eye - Number one!",
  '2': 'One Little Duck - Quack, quack, two!',
  '3': 'Cup of Tea - Number three, a cup of tea!',
  '4': 'Knock at the Door - Number four, knock, knock!',
  '5': 'Man Alive - Number five, man alive!',
  '6': 'Tom Mix - Number six, Tom Mix!',
  '7': 'Lucky Seven - Lucky number seven!',
  '8': 'Garden Gate - Number eight, open the gate!',
  '9': "Doctor's Orders - Number nine, doctor's orders!",
  '10': "David's Den - Number ten!",
  '11': 'Legs Eleven - Legs, eleven!',
  '12': 'One Dozen - Number twelve, a dozen!',
  '13': 'Unlucky for Some - Number thirteen, unlucky for some!',
  '14': "Valentine's Day - Number fourteen, Valentine's Day!",
  '15': 'Young and Keen - Number fifteen, young and keen!',
  '16': 'Sweet Sixteen - Number sixteen, sweet sixteen!',
  '17': 'Dancing Queen - Number seventeen, dancing queen!',
  '18': 'Coming of Age - Number eighteen, coming of age!',
  '19': 'Goodbye Teens - Number nineteen, goodbye teens!',
  '20': 'One Score - Number twenty, one score!',
  '21': 'Key of the Door - Number twenty-one, key of the door!',
  '22': 'Two Little Ducks - Quack, quack, twenty-two!',
  '23': 'Thee and Me - Number twenty-three, thee and me!',
  '24': 'Two Dozen - Number twenty-four, two dozen!',
  '25': 'Duck and Dive - Number twenty-five, duck and dive!',
  '26': 'Pick and Mix - Number twenty-six, pick and mix!',
  '27': 'Gateway to Heaven - Number twenty-seven, gateway to heaven!',
  '28': 'Overweight - Number twenty-eight, overweight!',
  '29': 'Rise and Shine - Number twenty-nine, rise and shine!',
  '30': 'Flirty Thirty - Number thirty, flirty thirty!',
  '31': 'Get Up and Run - Number thirty-one, get up and run!',
  '32': 'Buckle My Shoe - Number thirty-two, buckle my shoe!',
  '33': 'All the Threes - Number thirty-three, all the threes!',
  '34': 'Ask for More - Number thirty-four, ask for more!',
  '35': 'Jump and Jive - Number thirty-five, jump and jive!',
  '36': 'Three Dozen - Number thirty-six, three dozen!',
  '37': 'More Than Eleven - Number thirty-seven, more than eleven!',
  '38': 'Christmas Cake - Number thirty-eight, Christmas cake!',
  '39': 'Steps - Number thirty-nine, steps!',
  '40': 'Life Begins - Number forty, life begins!',
  '41': 'Time for Fun - Number forty-one, time for fun!',
  '42': 'Winnie the Pooh - Number forty-two, Winnie the Pooh!',
  '43': 'Down on Your Knees - Number forty-three, down on your knees!',
  '44': 'Droopy Drawers - Number forty-four, droopy drawers!',
  '45': 'Halfway There - Number forty-five, halfway there!',
  '46': 'Up to Tricks - Number forty-six, up to tricks!',
  '47': 'Four and Seven - Number forty-seven, four and seven!',
  '48': 'Four Dozen - Number forty-eight, four dozen!',
  '49': 'PC - Number forty-nine, PC!',
  '50': 'Bulls Eye - Number fifty, bulls eye!',
  '51': 'Tweak of the Thumb - Number fifty-one, tweak of the thumb!',
  '52': 'Danny La Rue - Number fifty-two, Danny La Rue!',
  '53': 'Stuck in the Tree - Number fifty-three, stuck in the tree!',
  '54': 'Clean the Floor - Number fifty-four, clean the floor!',
  '55': 'Snakes Alive - Number fifty-five, snakes alive!',
  '56': 'Was She Worth It? - Number fifty-six, was she worth it?',
  '57': 'Heinz Varieties - Number fifty-seven, Heinz varieties!',
  '58': 'Make Them Wait - Number fifty-eight, make them wait!',
  '59': 'Brighton Line - Number fifty-nine, Brighton line!',
  '60': "Grandma's House - Number sixty, grandma's house!",
  '61': "Baker's Bun - Number sixty-one, baker's bun!",
  '62': 'Turn the Screw - Number sixty-two, turn the screw!',
  '63': 'Tickety-Boo - Number sixty-three, tickety-boo!',
  '64': 'Red Raw - Number sixty-four, red raw!',
  '65': 'Old Age Pension - Number sixty-five, old age pension!',
  '66': 'Clickety-Click - Number sixty-six, clickety-click!',
  '67': 'Made in Heaven - Number sixty-seven, made in heaven!',
  '68': 'Saving Grace - Number sixty-eight, saving grace!',
  '69': 'Either Way Up - Number sixty-nine, either way up!',
  '70': 'Three Score and Ten - Number seventy, three score and ten!',
  '71': 'Bang on the Drum - Number seventy-one, bang on the drum!',
  '72': 'Six Dozen - Number seventy-two, six dozen!',
  '73': 'Queen Bee - Number seventy-three, queen bee!',
  '74': 'Candy Store - Number seventy-four, candy store!',
  '75': 'Strive and Strive - Number seventy-five, strive and strive!',
  '76': 'Was She Worth It? - Number seventy-six, was she worth it?',
  '77': 'Two Little Crutches - Number seventy-seven, two little crutches!',
  '78': '39 More Steps - Number seventy-eight, thirty-nine more steps!',
  '79': "Heaven's Gate - Number seventy-nine, heaven's gate!",
  '80': 'Eight and Blank - Number eighty, eight and blank!',
  '81': 'Stop and Run - Number eighty-one, stop and run!',
  '82': 'Straight on Through - Number eighty-two, straight on through!',
  '83': 'Time for Tea - Number eighty-three, time for tea!',
  '84': 'Seven Dozen - Number eighty-four, seven dozen!',
  '85': 'Staying Alive - Number eighty-five, staying alive!',
  '86': 'Between the Sticks - Number eighty-six, between the sticks!',
  '87': 'Torquay in Devon - Number eighty-seven, Torquay in Devon!',
  '88': 'Two Fat Ladies - Number eighty-eight, two fat ladies!',
  '89': 'Nearly There - Number eighty-nine, nearly there!',
  '90': 'Top of the Shop - Number'
};
